#!/bin/bash
# To narzędzie resetuje hasło dla aplikacji N8N zainstalwoanej na Mikrusie
# Autor: Jakub 'unknow' Mrugalski

# kolorki
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
NORMAL='\033[0m'

if [ ! -d /root/.n8n ]; then
    echo -e "${RED}Twoja instancja N8N nie jest zainstalowana w katalogu /root/.n8n";
    echo -e "Czy na pewno używałeś polecenia n8n_install do jej postawienia?${NORMAL}"
    exit 1
fi

n8nStatus=$(docker inspect -f '{{.State.Running}}' n8n 2>&1)

if [ "${n8nStatus}" == "true" ]; then
    echo -e "${GREEN}Usuwam konto użytkownika z N8N (scenariusze zostają)${NORMAL}"
    docker exec -it n8n n8n user-management:reset
    docker restart n8n
    echo -e "\n${GREEN}Za chwilę N8N uruchomi się ponownie - załóż nowego użytkownika${NORMAL}";
    exit 0
else
    echo -e "${RED}Kontener o nazwie N8N nie istnieje lub aplikacja nie skończyła startować${NORMAL}"
    exit 1
fi
