name: Test changed scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-test-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout generator repository
        uses: actions/checkout@v1
      - name: Test chce_LAMP.sh
        # todo: run only on file changed
        run: |
          sudo ./scripts/chce_LAMP.sh
          # sudo ./tests/chce_LAMP_test.sh
